project:
  type: website
  output-dir: docs

website:
  title: "Lars Schöbitz"
  site-url: "https://rainbow-train.github.io/website/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides/
        text: Slides
      - href: posts/
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto



